name: MapReset
version: 1.0.0
api: 1.0.0
description: Read Readme Guys 
main: MapReset\Main
author: [Praxthisnovcht, xFlare]
commands:
    mapreset:
        description: Resets the map when this command is used.
